#!/usr/bin/env bash
# Bootstrap Claude Code config on this machine.
#
#   ./bootstrap.sh --instance <dir>  install the instance at <dir> on top of this
#                             base (the mechanism); it will become required
#   ./bootstrap.sh --check    report drift, change nothing (exit 1 if drift)
#   ./bootstrap.sh --no-timer install, but leave the weekly report timer alone
#   ./bootstrap.sh --allow-worktree  install from a linked git worktree anyway
#                             (refused by default — see section 0)
#
# Exit codes: 0 done or in sync; 1 drift (--check) or a refused install;
# 64 a usage error.
#
# Idempotent: safe to re-run after every git pull.
#
# Two roots. The BASE is this checkout, or a snapshot of it under the store:
# hooks/ bin/ commands/ agents/ skills/ output-styles/ and settings.base.json.
# The INSTANCE is the directory given to --instance: rules/, CLAUDE.md,
# settings.instance.json, machine.json and instance.json. Without --instance
# the checkout is both (the single-root install this script used to be).
#
# Layout:
#   settings.base.json       the base's, identical on every machine
#   settings.instance.json   the instance's
#   machine.json             gitignored, this machine's paths and env
#   ~/.claude/settings.json  generated by merging the three, in that order
#   hooks/ bin/ commands/ agents/ skills/ output-styles/  symlinked from the base
#   rules/ CLAUDE.md                                      symlinked from the instance

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
CHECK_ONLY=0
WITH_TIMER=1
ALLOW_WORKTREE=0
INSTANCE_ARG=""
usage_error() { echo "$1 (want --instance <dir>, --check, --no-timer, --allow-worktree)" >&2; exit 64; }
while [[ $# -gt 0 ]]; do
  case "$1" in
    --check)          CHECK_ONLY=1 ;;
    --no-timer)       WITH_TIMER=0 ;;
    --allow-worktree) ALLOW_WORKTREE=1 ;;
    --instance)
      [[ $# -ge 2 && -n "$2" && "$2" != --* ]] || usage_error "--instance needs a directory"
      INSTANCE_ARG="$2"; shift ;;
    *)                usage_error "unknown option: $1" ;;
  esac
  shift
done

drift=0
# Set by a step that failed without dying (the observer probe). Retention
# deletes nothing after one; ordinary drift, such as a first install's changes,
# is not red.
red=0
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
note() { printf '  \033[33m→\033[0m %s\n' "$1"; drift=1; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }
# A step that deliberately did nothing. Distinct from note(): it must NOT set
# drift, or `--check` in a sandbox would report drift that does not exist, and
# it must not print the arrow that the idempotency test greps for.
skip() { printf '  \033[90m·\033[0m %s\n' "$1"; }

command -v python3 >/dev/null 2>&1 || die "python3 is required"

BASE="$REPO"   # the mechanism: this checkout, or a snapshot under the store
INSTANCE=""
if [[ -n "$INSTANCE_ARG" ]]; then
  INSTANCE=$(cd -P "$INSTANCE_ARG" 2>/dev/null && pwd -P) \
    || die "--instance $INSTANCE_ARG is not a directory"
  [[ -d "$INSTANCE/rules" ]] || die "--instance $INSTANCE has no rules/, so it is not an instance"
fi
STORE="${XDG_DATA_HOME:-$HOME/.local/share}/trimtab/core"

echo "base:  $BASE"
echo "instance: ${INSTANCE:-$BASE (single root)}"
echo "target: $CLAUDE_HOME"
echo
if [[ -z "$INSTANCE" ]]; then
  skip "no --instance: installing this checkout as both base and instance (deprecated; --instance will be required)"
  INSTANCE="$REPO"
  SINGLE_ROOT=1
else
  SINGLE_ROOT=0
fi

# ---- 0. refuse a non-canonical checkout --------------------------------
# Every step below points the live tree at $REPO: hooks/, bin/, rules/,
# CLAUDE.md, the generated settings.json and the systemd units. $REPO is
# wherever this script happens to sit, so running it from a git worktree
# installs THAT worktree — and worktrees are disposable. Remove one afterwards
# and $CLAUDE_HOME/hooks dangles; Claude Code treats a hook that fails to
# execute as non-blocking, so all three guards stop enforcing with no signal.
# Guards absent is indistinguishable from guards allowing everything, which is
# the failure this repo exists to prevent — so this is refused, not warned
# about. It has already happened once: the live systemd units were found
# pointing into a merged worktree.
#
# Not covered: an install from a copy of the tree that is not a git checkout at
# all. `git` cannot answer there, and refusing would break a legitimate
# tarball install, so that case proceeds. The target is the accidental
# worktree run, not a determined operator.
# See docs/adr/0006-bootstrap-installs-only-from-the-canonical-checkout.md.
#
# Both sides of the comparison must be physical paths. `pwd` is logical by
# default, so $REPO keeps any symlinked ancestor intact (a dotfiles-style
# ~/dotfiles/harness -> ~/repos/harness), while `git -C` chdirs and
# resolves through getcwd(), which always answers physically. Comparing the two
# as-is refused a perfectly canonical clone reached through a symlink, and told
# the operator it was a linked worktree while naming a different path as
# canonical. $REPO itself stays logical: it is what every link created below
# points at, and changing that is a separate decision from fixing this check.
git_common=$(git -C "$REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)
if [[ -n "$git_common" ]]; then
  canonical="${git_common%/}"; canonical="${canonical%/.git}"
  repo_phys=$(cd -P "$REPO" 2>/dev/null && pwd -P) || repo_phys="$REPO"
  if [[ "$canonical" != "$repo_phys" ]]; then
    if [[ $ALLOW_WORKTREE -eq 1 ]]; then
      skip "installing from a linked worktree at the operator's request: $REPO"
    else
      die "refusing to install from a linked worktree:
      $REPO
  The canonical checkout is:
      $canonical
  Every link this script creates would point into a tree that is meant to be
  deleted, and a dangling $CLAUDE_HOME/hooks means the guards stop enforcing
  silently. Re-run from the canonical checkout, or pass --allow-worktree if
  that is genuinely what you want."
    fi
  fi
fi

# Is this a live install, or a test/CI run pointed at a throwaway directory?
# Only the systemd step needs to know: everything else already writes strictly
# inside $CLAUDE_HOME, but a user timer lives in the operator's own session and
# cannot be sandboxed by pointing CLAUDE_CONFIG_DIR somewhere else.
SANDBOXED=0
if [[ -n "${CLAUDE_CONFIG_DIR:-}" && "${CLAUDE_CONFIG_DIR%/}" != "${HOME%/}/.claude" ]]; then
  SANDBOXED=1
fi

# ---- 1. machine.json ---------------------------------------------------
# Lives in the instance: it is this machine's values for that instance.
if [[ ! -f "$INSTANCE/machine.json" ]]; then
  if [[ $CHECK_ONLY -eq 1 ]]; then
    note "machine.json missing"
  else
    sed "s|/home/CHANGEME/|$HOME/|g" "$BASE/machine.example.json" > "$INSTANCE/machine.json"
    note "created machine.json from example — edit it for this host"
  fi
else
  ok "machine.json present"
fi

# ---- 1b. the doctrine registry check (D10) ----------------------------
# Before anything is written: a failure leaves the previous install live, and
# nothing is switched or deleted. Only with --instance; the single-root install
# has no separate doctrine to check.
installed_json="$STORE/.installed.json"
values=""
if [[ $SINGLE_ROOT -eq 0 ]]; then
  TRIMTAB_BIN="$BASE/bin/trimtab"
  against=()
  prev_instance_sha=$(python3 - "$installed_json" "$INSTANCE" <<'PY' 2>/dev/null || true
import json, sys
try:
    rec = json.load(open(sys.argv[1]))
except (OSError, ValueError):
    sys.exit(0)
if rec.get("instance_root") == sys.argv[2] and isinstance(rec.get("instance_sha"), str):
    print(rec["instance_sha"])
PY
)
  [[ "$prev_instance_sha" =~ ^[0-9a-f]{40}$ ]] && against=(--against "$prev_instance_sha")
  if ! reg_out=$("$TRIMTAB_BIN" registry --check --instance "$INSTANCE" ${against[@]+"${against[@]}"} 2>&1); then
    printf '%s\n' "$reg_out" >&2
    die "the instance's doctrine fails the registry check; nothing was changed, the previous install stays live"
  fi
  ok "doctrine registry check passed"
  values=$("$TRIMTAB_BIN" instance --json --instance "$INSTANCE") \
    || die "the instance's instance.json is invalid; nothing was changed"
fi

# ---- 2. generate settings.json ----------------------------------------
# Three layers, in order: the base, the instance, this machine. Dicts recurse,
# lists concatenate without duplicates, scalars override. After every layer the
# base's hook registrations must still be present: a layer that loses one would
# switch a guard off silently, so the merge refuses and nothing is written.
mkdir -p "$CLAUDE_HOME"
generated=$(python3 - "$BASE" "$INSTANCE" "${values:-}" <<'PY'
import json, sys, os
base_root, inst_root, values = sys.argv[1], sys.argv[2], sys.argv[3]
def load(root, name):
    try:
        with open(os.path.join(root, name)) as f: return json.load(f)
    except FileNotFoundError:
        return {}

def merge(a, b):
    """b wins on scalars; dicts recurse; lists concatenate without duplicates."""
    out = dict(a)
    for k, v in b.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = merge(out[k], v)
        elif k in out and isinstance(out[k], list) and isinstance(v, list):
            seen, combined = set(), []
            for item in out[k] + v:
                key = json.dumps(item, sort_keys=True)
                if key not in seen:
                    seen.add(key); combined.append(item)
            out[k] = combined
        else:
            out[k] = v
    return out

layers = [("settings.base.json", load(base_root, "settings.base.json"))]
if inst_root != base_root:
    layers.append(("settings.instance.json", load(inst_root, "settings.instance.json")))
layers.append(("machine.json", load(inst_root, "machine.json")))

base_hooks = layers[0][1].get("hooks", {})
def refuse(layer, why):
    print(f"REFUSED: {layer} {why}; the guards would not run. Nothing was changed.", file=sys.stderr)
    sys.exit(3)
merged = {}
for name, layer in layers:
    merged = merge(merged, layer)
    hooks = merged.get("hooks", {})
    if not isinstance(hooks, dict):
        refuse(name, "replaces `hooks` with something that is not an object")
    for event, groups in base_hooks.items():
        have = hooks.get(event)
        if not isinstance(have, list) or any(g not in have for g in groups):
            refuse(name, f"drops a {event} hook registration the base requires")
    if merged.get("disableAllHooks"):
        refuse(name, "sets disableAllHooks")

# Bootstrap owns the TRIMTAB_* env keys: the instance's root changes per
# machine, and the pack switch and private pattern file come from the
# validated instance.json, never from a settings layer.
env = merged.setdefault("env", {})
owned = {"TRIMTAB_INSTANCE": inst_root}
if values:
    v = json.loads(values)
    owned["TRIMTAB_SECRET_PACKS"] = v["env"]["TRIMTAB_SECRET_PACKS"]
    owned["TRIMTAB_SECRET_PATTERNS"] = v["env"]["TRIMTAB_SECRET_PATTERNS"]
for key, value in owned.items():
    prior = env.get(key)
    if prior is not None and prior != value:
        print(f"note: a settings layer set {key}; bootstrap owns it and wrote {value!r}", file=sys.stderr)
    if value is None:
        env.pop(key, None)
    else:
        env[key] = value
merged.pop("_comment", None)
# Drop empty containers so the file stays readable
def prune(o):
    if isinstance(o, dict):
        return {k: prune(v) for k, v in o.items() if v not in ({}, [], None)}
    return o
print(json.dumps(prune(merged), indent=2))
PY
) || die "settings merge refused (see above); nothing was changed"

target="$CLAUDE_HOME/settings.json"
if [[ -f "$target" ]] && [[ "$(cat "$target")" == "$generated" ]]; then
  ok "settings.json up to date"
elif [[ $CHECK_ONLY -eq 1 ]]; then
  note "settings.json would change"
else
  if [[ -f "$target" ]]; then
    cp "$target" "$target.bak.$(date +%Y%m%d%H%M%S)"
    printf '%s\n' "$generated" > "$target"
    note "wrote settings.json (previous version backed up)"
  else
    printf '%s\n' "$generated" > "$target"
    note "wrote settings.json"
  fi
fi
# A relative private pattern path in the live file means the guards that read
# it would block every call (they refuse a relative value), whatever the
# comparison above found: name it.
if [[ $CHECK_ONLY -eq 1 && -f "$target" ]]; then
  live_pat=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("env",{}).get("TRIMTAB_SECRET_PATTERNS",""))' "$target" 2>/dev/null || true)
  if [[ -n "$live_pat" && "$live_pat" != /* ]]; then
    note "TRIMTAB_SECRET_PATTERNS in settings.json is not an absolute path"
  fi
fi

# ---- 3. symlink directories -------------------------------------------
# Only directories Claude Code itself recognises belong under ~/.claude —
# docs/ deliberately stays in the repo rather than being linked in. The
# mechanism links from the base; the doctrine (rules/) from the instance.
for dir in hooks bin rules commands agents skills output-styles; do
  if [[ "$dir" == rules ]]; then src="$INSTANCE/$dir"; else src="$BASE/$dir"; fi
  [[ -d "$src" ]] || continue
  dst="$CLAUDE_HOME/$dir"
  if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
    ok "$dir/ linked"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    # Name where it actually points. "not linked" is true of a link into a
    # deleted worktree, a link into another checkout and no link at all, and
    # those need different fixes — the bare message sent the last investigation
    # looking for a missing file that was in fact a wrong target.
    if [[ -L "$dst" ]]; then
      note "$dir/ points at $(readlink "$dst") — expected $src"
    else
      note "$dir/ not linked"
    fi
  else
    if [[ -e "$dst" && ! -L "$dst" ]]; then
      mv "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
      note "moved existing $dir/ aside"
    fi
    rm -f "$dst"
    ln -s "$src" "$dst"
    note "linked $dir/"
  fi
done

# ---- 4. CLAUDE.md ------------------------------------------------------
if [[ -f "$INSTANCE/CLAUDE.md" ]]; then
  dst="$CLAUDE_HOME/CLAUDE.md"
  if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$INSTANCE/CLAUDE.md")" ]]; then
    ok "CLAUDE.md linked"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    note "CLAUDE.md not linked"
  else
    [[ -e "$dst" && ! -L "$dst" ]] && mv "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
    rm -f "$dst"; ln -s "$INSTANCE/CLAUDE.md" "$dst"; note "linked CLAUDE.md"
  fi
fi

# ---- 5. verify hooks are runnable -------------------------------------
echo
for h in "$BASE"/hooks/*.sh "$BASE"/bin/*.sh "$BASE"/bin/*.py; do
  [[ -e "$h" ]] || continue
  name=$(basename "$h")
  if [[ ! -x "$h" ]]; then
    if [[ $CHECK_ONLY -eq 1 ]]; then note "$name not executable"
    else chmod +x "$h"; note "chmod +x $name"; fi
  else
    ok "$name executable"
  fi
done

# A hook that cannot run, or that cannot parse its payload, fails OPEN
# upstream (only exit 2 blocks), so prove blocking works end to end through
# the symlink — for every guard, both on a payload it must block and on a
# garbage payload. A guard that is never probed can install broken and the run
# still reports "done.".
#
#   probe_guard <hook> <what it blocks> <payload that must block>
probe_guard() {
  local hook="$1" what="$2" probe="$3" name="${1%.sh}" rc rc_garbage
  if [[ -x "$CLAUDE_HOME/hooks/$hook" ]]; then
    set +e
    printf '%s' "$probe" | "$CLAUDE_HOME/hooks/$hook" >/dev/null 2>&1
    rc=$?
    printf '%s' 'not json' | "$CLAUDE_HOME/hooks/$hook" >/dev/null 2>&1
    rc_garbage=$?
    set -e
    # die, not note: a guard returning anything but 2 is not drift, it is absent.
    # note sets drift=1, which in install mode prints a yellow arrow and then
    # reports "done." — an install that says done while the guards are open is
    # exactly the silent failure ADR 0001 refuses for the observer.
    [[ $rc -eq 2 ]] && ok "$name blocks $what through the symlink" \
                    || die "$name returned $rc, expected 2 — the guards are failing open"
    [[ $rc_garbage -eq 2 ]] && ok "$name fails closed on an unparseable payload" \
                            || die "$name returned $rc_garbage on garbage, expected 2 — fails open"
  else
    # After section 3 links hooks/ and the chmod loop above marks them
    # executable, this branch is unreachable in an install — so reaching it means
    # an invariant broke between here and there, and that must be loud. Under
    # --check, an unlinked hooks/ is ordinary drift and section 3 already noted
    # it; reporting rather than dying is what --check is for.
    if [[ $CHECK_ONLY -eq 1 ]]; then
      note "$hook not linked into $CLAUDE_HOME — guard probe skipped"
    else
      die "$hook not linked into $CLAUDE_HOME after section 3 — refusing to report a successful install with unverified guards"
    fi
  fi
}

# The PEM header is assembled at runtime, as in tests/guard-tests.sh, so no
# literal key header ever appears in this file: guard-secrets would refuse the
# edit that wrote it, and every secret scanner would flag the repo.
pem="-----BEGIN RSA PRIVATE"
pem="$pem KEY-----"
probe_guard guard-bash.sh "a destructive command" \
  '{"tool_name":"Bash","tool_input":{"command":"terraform destroy"}}'
probe_guard guard-paths.sh "a read of a .env file" \
  '{"tool_name":"Read","tool_input":{"file_path":"/x/.env"}}'
probe_guard guard-secrets.sh "a PEM private key in written content" \
  "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"/tmp/x/probe.py\",\"content\":\"KEY = '$pem'\"}}"
# Each enabled signature pack must block its own sample (stage S2, C8). The
# switch comes from the generated settings, not this shell: unset or empty
# means every shipped pack, "none" means no pack.
packs=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("env",{}).get("TRIMTAB_SECRET_PACKS",""))' \
        "$CLAUDE_HOME/settings.json" 2>/dev/null || true)
pack_list=()
if [[ -z "$packs" ]]; then
  for f in "$BASE"/hooks/secrets.d/*.patterns; do
    [[ -e "$f" ]] || continue
    f=${f##*/}; pack_list+=("${f%.patterns}")
  done
elif [[ "$packs" != none ]]; then
  IFS=',' read -r -a pack_list <<<"$packs"
fi
for pack in ${pack_list[@]+"${pack_list[@]}"}; do
  probe_file="$BASE/hooks/secrets.d/$pack.probe"
  [[ -r "$probe_file" ]] || die "signature pack $pack has no probe file"
  while IFS= read -r first && IFS= read -r rest; do
    [[ -z "$first" ]] && continue
    sample="$first$rest"
    TRIMTAB_SECRET_PACKS="$pack" probe_guard guard-secrets.sh "a $pack sample" \
      "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"/tmp/x/probe.py\",\"content\":\"v = '$sample'\"}}"
    IFS= read -r _ || true
  done <"$probe_file"
done
probe_guard guard-security.sh "an edit to a CI workflow" \
  '{"tool_name":"Edit","tool_input":{"file_path":"/tmp/x/.github/workflows/ci.yml"}}'
unset pem
# The declared private pattern file must parse with guard-secrets' own parser:
# a benign write has to pass with it. The guard refuses a relative path or an
# unreadable file, so a bad declaration fails here and not on the first edit.
pat=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("env",{}).get("TRIMTAB_SECRET_PATTERNS",""))' \
      "$CLAUDE_HOME/settings.json" 2>/dev/null || true)
if [[ -n "$pat" && -x "$CLAUDE_HOME/hooks/guard-secrets.sh" ]]; then
  set +e
  printf '%s' '{"tool_name":"Write","tool_input":{"file_path":"/tmp/x/probe.py","content":"print(42)"}}' \
    | TRIMTAB_SECRET_PATTERNS="$pat" "$CLAUDE_HOME/hooks/guard-secrets.sh" >/dev/null 2>&1
  rc_pat=$?
  set -e
  if [[ $rc_pat -eq 0 ]]; then
    ok "the private pattern file parses with guard-secrets' own parser"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    note "guard-secrets returned $rc_pat on benign content with the declared TRIMTAB_SECRET_PATTERNS — it is relative, unreadable or does not parse"
  else
    die "guard-secrets returned $rc_pat on benign content with the private pattern file — it does not parse, or cannot be read"
  fi
fi

# ---- 6. verify the rule-usage observer records ------------------------
# This hook cannot block anything, so the only failure it can have is
# silence — and silence reads exactly like a quiet week in the weekly
# report. Prove end to end, through the symlink, that a payload becomes a
# record with a measured size on it.
if [[ -x "$CLAUDE_HOME/hooks/rule-usage.sh" ]]; then
  probe_log=$(mktemp -t rule-usage-probe.XXXXXX)
  # Any file in the checkout will do, as long as it exists: the observer
  # records its size, and a missing file records null, which reads as failure.
  # README.md is the one every checkout has (trimtab-core ships no CLAUDE.md).
  probe='{"hook_event_name":"InstructionsLoaded","session_id":"bootstrap-probe","cwd":"/","file_path":"'"$BASE/README.md"'","memory_type":"User","load_reason":"session_start"}'
  set +e
  printf '%s' "$probe" \
    | CLAUDE_RULE_USAGE_LOG="$probe_log" "$CLAUDE_HOME/hooks/rule-usage.sh" >/dev/null 2>&1
  rc_obs=$?
  set -e
  if [[ $rc_obs -eq 0 ]] \
     && grep -q '"event":"InstructionsLoaded"' "$probe_log" 2>/dev/null \
     && grep -q '"bytes":[0-9]' "$probe_log" 2>/dev/null; then
    ok "rule-usage observer records a load through the symlink"
  else
    note "rule-usage observer wrote no usable record (exit $rc_obs) — the weekly report would read as a quiet week"
    red=1
  fi
  rm -f "$probe_log"
else
  note "rule-usage.sh not linked into $CLAUDE_HOME yet — observer probe skipped"
fi

# ---- 6b. the install record, and retention (D2) -----------------------
# Reaching this point means no step died: the registry check, the merge, the
# links and every guard probe are green. Retention runs only then, and only
# when this script is itself a snapshot under the store (a directory named by
# its own 40-hex HEAD). It deletes 40-hex directories other than the live one
# and its predecessor, and nothing else in the store. --check is the dry run.
#
# The store belongs to the live install: its record names the snapshots the live
# links point into. A sandboxed run (a config dir other than the live one) that
# did not bring its own XDG_DATA_HOME would reach that store through $HOME, and
# could overwrite the record or delete a snapshot the live install still uses.
# It leaves both alone.
if [[ $SINGLE_ROOT -eq 0 && $red -eq 0 && $SANDBOXED -eq 1 && -z "${XDG_DATA_HOME:-}" ]]; then
  skip "sandboxed run without its own XDG_DATA_HOME: install record and retention left alone (the store belongs to the live install)"
elif [[ $SINGLE_ROOT -eq 0 && $red -eq 0 ]]; then
  base_sha=$(git -C "$BASE" rev-parse HEAD 2>/dev/null || true)
  store_phys=$(cd -P "$STORE" 2>/dev/null && pwd -P || true)
  base_parent=$(cd -P "$BASE/.." && pwd -P)
  # The predecessor is the previous *different* base. A re-run from the same base
  # keeps the one already recorded, or the rollback snapshot would be lost to any
  # no-op re-run. Read before the record is rewritten below; "-" is an empty field.
  read -r rec_base rec_prev < <(python3 -c '
import json, sys
r = json.load(open(sys.argv[1]))
print(r.get("base_sha") or "-", r.get("prev_base_sha") or "-")' "$installed_json" 2>/dev/null || echo "- -")
  [[ "$rec_base" == - ]] && rec_base=""
  [[ "$rec_prev" == - ]] && rec_prev=""
  if [[ "$rec_base" == "$base_sha" ]]; then prev_base="$rec_prev"; else prev_base="$rec_base"; fi
  if [[ -n "$store_phys" && "$base_parent" == "$store_phys" \
        && "$base_sha" =~ ^[0-9a-f]{40}$ && "${BASE##*/}" == "$base_sha" ]]; then
    for d in "$STORE"/*/; do
      d=${d%/}; name=${d##*/}
      [[ "$name" =~ ^[0-9a-f]{40}$ ]] || continue          # snapshots only, never anything else
      [[ "$name" == "$base_sha" || "$name" == "$prev_base" ]] && continue
      if [[ $CHECK_ONLY -eq 1 ]]; then
        skip "retention would delete snapshot $name"       # the dry run
      else
        rm -rf -- "$d" && printf '  \033[33m-\033[0m deleted old snapshot %s\n' "$name"
      fi
    done
  fi
  if [[ $CHECK_ONLY -eq 0 ]]; then
    inst_sha=$(git -C "$INSTANCE" rev-parse HEAD 2>/dev/null || true)
    mkdir -p "$STORE"
    python3 - "$installed_json" "$INSTANCE" "$inst_sha" "$base_sha" "$prev_base" <<'PY'
import json, os, sys, tempfile
path, root, inst, base, prev = sys.argv[1:]
sha = lambda s: s if len(s) == 40 else None
fd, tmp = tempfile.mkstemp(dir=os.path.dirname(path))
try:
    with os.fdopen(fd, "w") as f:
        json.dump({"instance_root": root, "instance_sha": sha(inst), "base_sha": sha(base),
                   "prev_base_sha": sha(prev)}, f)
    os.replace(tmp, path)
finally:
    if os.path.exists(tmp):
        os.unlink(tmp)
PY
  fi
fi

# ---- 7. weekly report timer -------------------------------------------
# A *user* timer: it runs as the operator, reads only their own log, writes
# only into their own log directory, and is undone with
#   systemctl --user disable --now rule-usage-report.timer
# Skip the whole step with --no-timer on a machine that should not report.
# A user timer lives in the operator's own systemd session, which no
# CLAUDE_CONFIG_DIR can redirect. This step used $HOME unconditionally, so a run
# that had declared itself sandboxed — ci.yml's own bootstrap job sets
# CLAUDE_CONFIG_DIR=/tmp/claude-ci-home — still rewired the operator's systemd
# when it happened on a workstation instead of a runner. Combined with §0 that
# is how the live units came to point into a worktree: enabled, working, and
# one cleanup away from silently never running again. A sandbox gets no timer.
if [[ $WITH_TIMER -eq 1 && $SANDBOXED -eq 1 ]]; then
  echo
  skip "sandboxed run (CLAUDE_CONFIG_DIR is not $HOME/.claude) — timer left alone"
elif [[ $WITH_TIMER -eq 1 && -d "$REPO/systemd" ]] && command -v systemctl >/dev/null 2>&1; then
  echo
  # XDG_CONFIG_HOME is the correct spelling of this location; $HOME/.config is
  # only its default.
  unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  [[ $CHECK_ONLY -eq 1 ]] || mkdir -p "$unit_dir"
  for unit in "$REPO"/systemd/*; do
    [[ -e "$unit" ]] || continue
    uname=$(basename "$unit")
    dst="$unit_dir/$uname"
    if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$unit")" ]]; then
      ok "$uname linked"
    elif [[ $CHECK_ONLY -eq 1 ]]; then
      # Same reason as the directory links above: a unit pointing into a
      # worktree reads as "not linked", which is how this went undiagnosed.
      if [[ -L "$dst" ]]; then
        note "$uname points at $(readlink "$dst") — expected $unit"
      else
        note "$uname not linked"
      fi
    else
      ln -sfn "$unit" "$dst"
      note "linked $uname"
    fi
  done

  if systemctl --user is-enabled rule-usage-report.timer >/dev/null 2>&1; then
    ok "rule-usage-report.timer enabled"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    note "rule-usage-report.timer not enabled"
  elif ! systemctl --user daemon-reload >/dev/null 2>&1; then
    note "no user systemd session here — enable it yourself with: systemctl --user enable --now rule-usage-report.timer"
  elif systemctl --user enable --now rule-usage-report.timer >/dev/null 2>&1; then
    note "enabled rule-usage-report.timer (Mondays, 08:00)"
  else
    note "could not enable rule-usage-report.timer — run: systemctl --user enable --now rule-usage-report.timer"
  fi
fi

echo
if [[ $CHECK_ONLY -eq 1 ]]; then
  [[ $drift -eq 1 ]] && { echo "drift detected"; exit 1; } || { echo "in sync"; exit 0; }
fi
echo "done. Run 'claude' and check /hooks to confirm registration."
