#!/usr/bin/env bash
# Bootstrap Claude Code config on this machine.
#
#   ./bootstrap.sh            install / re-sync
#   ./bootstrap.sh --check    report drift, change nothing (exit 1 if drift)
#   ./bootstrap.sh --no-timer install, but leave the weekly report timer alone
#   ./bootstrap.sh --allow-worktree  install from a linked git worktree anyway
#                             (refused by default — see section 0)
#
# Idempotent: safe to re-run after every git pull.
#
# Layout:
#   settings.base.json   versioned, identical on every machine
#   machine.json         gitignored, this machine's paths and env
#   ~/.claude/settings.json  generated by merging the two
#   hooks/ bin/ rules/ commands/ agents/ skills/ output-styles/  symlinked into ~/.claude/

set -euo pipefail

REPO="$(cd "$(dirname "${BASH_SOURCE[0]}")" && pwd)"
CLAUDE_HOME="${CLAUDE_CONFIG_DIR:-$HOME/.claude}"
CHECK_ONLY=0
WITH_TIMER=1
ALLOW_WORKTREE=0
for arg in "$@"; do
  case "$arg" in
    --check)          CHECK_ONLY=1 ;;
    --no-timer)       WITH_TIMER=0 ;;
    --allow-worktree) ALLOW_WORKTREE=1 ;;
    *)          echo "unknown option: $arg (want --check, --no-timer, --allow-worktree)" >&2; exit 64 ;;
  esac
done

drift=0
ok()   { printf '  \033[32m✓\033[0m %s\n' "$1"; }
note() { printf '  \033[33m→\033[0m %s\n' "$1"; drift=1; }
die()  { printf '  \033[31m✗\033[0m %s\n' "$1" >&2; exit 1; }
# A step that deliberately did nothing. Distinct from note(): it must NOT set
# drift, or `--check` in a sandbox would report drift that does not exist, and
# it must not print the arrow that the idempotency test greps for.
skip() { printf '  \033[90m·\033[0m %s\n' "$1"; }

command -v python3 >/dev/null 2>&1 || die "python3 is required"

echo "repo:  $REPO"
echo "target: $CLAUDE_HOME"
echo

# ---- 0. refuse a non-canonical checkout --------------------------------
# Every step below points the live tree at $REPO: hooks/, bin/, rules/,
# CLAUDE.md, the generated settings.json and the systemd units. $REPO is
# wherever this script happens to sit, so running it from a git worktree
# installs THAT worktree — and worktrees are disposable. Remove one afterwards
# and $CLAUDE_HOME/hooks dangles; Claude Code treats a hook that fails to
# execute as non-blocking, so all three guards stop enforcing with no signal.
# Guards absent is indistinguishable from guards allowing everything, which is
# the failure this repo exists to prevent — so this is refused, not warned
# about. It has already happened once: the live systemd units were found
# pointing into a merged worktree.
#
# Not covered: an install from a copy of the tree that is not a git checkout at
# all. `git` cannot answer there, and refusing would break a legitimate
# tarball install, so that case proceeds. The target is the accidental
# worktree run, not a determined operator.
# See docs/adr/0006-bootstrap-installs-only-from-the-canonical-checkout.md.
#
# Both sides of the comparison must be physical paths. `pwd` is logical by
# default, so $REPO keeps any symlinked ancestor intact (a dotfiles-style
# ~/dotfiles/harness -> ~/repos/harness), while `git -C` chdirs and
# resolves through getcwd(), which always answers physically. Comparing the two
# as-is refused a perfectly canonical clone reached through a symlink, and told
# the operator it was a linked worktree while naming a different path as
# canonical. $REPO itself stays logical: it is what every link created below
# points at, and changing that is a separate decision from fixing this check.
git_common=$(git -C "$REPO" rev-parse --path-format=absolute --git-common-dir 2>/dev/null || true)
if [[ -n "$git_common" ]]; then
  canonical="${git_common%/}"; canonical="${canonical%/.git}"
  repo_phys=$(cd -P "$REPO" 2>/dev/null && pwd -P) || repo_phys="$REPO"
  if [[ "$canonical" != "$repo_phys" ]]; then
    if [[ $ALLOW_WORKTREE -eq 1 ]]; then
      skip "installing from a linked worktree at the operator's request: $REPO"
    else
      die "refusing to install from a linked worktree:
      $REPO
  The canonical checkout is:
      $canonical
  Every link this script creates would point into a tree that is meant to be
  deleted, and a dangling $CLAUDE_HOME/hooks means the guards stop enforcing
  silently. Re-run from the canonical checkout, or pass --allow-worktree if
  that is genuinely what you want."
    fi
  fi
fi

# Is this a live install, or a test/CI run pointed at a throwaway directory?
# Only the systemd step needs to know: everything else already writes strictly
# inside $CLAUDE_HOME, but a user timer lives in the operator's own session and
# cannot be sandboxed by pointing CLAUDE_CONFIG_DIR somewhere else.
SANDBOXED=0
if [[ -n "${CLAUDE_CONFIG_DIR:-}" && "${CLAUDE_CONFIG_DIR%/}" != "${HOME%/}/.claude" ]]; then
  SANDBOXED=1
fi

# ---- 1. machine.json ---------------------------------------------------
if [[ ! -f "$REPO/machine.json" ]]; then
  if [[ $CHECK_ONLY -eq 1 ]]; then
    note "machine.json missing"
  else
    sed "s|/home/CHANGEME/|$HOME/|g" "$REPO/machine.example.json" > "$REPO/machine.json"
    note "created machine.json from example — edit it for this host"
  fi
else
  ok "machine.json present"
fi

# ---- 2. generate settings.json ----------------------------------------
mkdir -p "$CLAUDE_HOME"
generated=$(python3 - "$REPO" <<'PY'
import json, sys, os
repo = sys.argv[1]
def load(p):
    try:
        with open(os.path.join(repo, p)) as f: return json.load(f)
    except FileNotFoundError:
        return {}

def merge(a, b):
    """b wins on scalars; dicts recurse; lists concatenate without duplicates."""
    out = dict(a)
    for k, v in b.items():
        if k in out and isinstance(out[k], dict) and isinstance(v, dict):
            out[k] = merge(out[k], v)
        elif k in out and isinstance(out[k], list) and isinstance(v, list):
            seen, combined = set(), []
            for item in out[k] + v:
                key = json.dumps(item, sort_keys=True)
                if key not in seen:
                    seen.add(key); combined.append(item)
            out[k] = combined
        else:
            out[k] = v
    return out

merged = merge(load("settings.base.json"), load("machine.json"))
# Stage S2 (docs/plans/0013-trimtab-split-stage2.md, S2-2): the package reads
# its doctrine only from an explicit instance root. The value is this
# checkout's path, which differs per machine, so bootstrap computes it rather
# than settings.base.json carrying a constant. Bootstrap owns the key.
env = merged.setdefault("env", {})
prior = env.get("TRIMTAB_INSTANCE")
env["TRIMTAB_INSTANCE"] = repo
if prior not in (None, repo):
    print(f"note: machine.json set TRIMTAB_INSTANCE={prior!r}; bootstrap owns it and wrote {repo!r}",
          file=sys.stderr)
merged.pop("_comment", None)
# Drop empty containers so the file stays readable
def prune(o):
    if isinstance(o, dict):
        return {k: prune(v) for k, v in o.items() if v not in ({}, [], None)}
    return o
print(json.dumps(prune(merged), indent=2))
PY
)

target="$CLAUDE_HOME/settings.json"
if [[ -f "$target" ]] && [[ "$(cat "$target")" == "$generated" ]]; then
  ok "settings.json up to date"
elif [[ $CHECK_ONLY -eq 1 ]]; then
  note "settings.json would change"
else
  if [[ -f "$target" ]]; then
    cp "$target" "$target.bak.$(date +%Y%m%d%H%M%S)"
    printf '%s\n' "$generated" > "$target"
    note "wrote settings.json (previous version backed up)"
  else
    printf '%s\n' "$generated" > "$target"
    note "wrote settings.json"
  fi
fi

# ---- 3. symlink directories -------------------------------------------
# Only directories Claude Code itself recognises belong under ~/.claude —
# docs/ deliberately stays in the repo rather than being linked in.
for dir in hooks bin rules commands agents skills output-styles; do
  src="$REPO/$dir"
  [[ -d "$src" ]] || continue
  dst="$CLAUDE_HOME/$dir"
  if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$src")" ]]; then
    ok "$dir/ linked"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    # Name where it actually points. "not linked" is true of a link into a
    # deleted worktree, a link into another checkout and no link at all, and
    # those need different fixes — the bare message sent the last investigation
    # looking for a missing file that was in fact a wrong target.
    if [[ -L "$dst" ]]; then
      note "$dir/ points at $(readlink "$dst") — expected $src"
    else
      note "$dir/ not linked"
    fi
  else
    if [[ -e "$dst" && ! -L "$dst" ]]; then
      mv "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
      note "moved existing $dir/ aside"
    fi
    rm -f "$dst"
    ln -s "$src" "$dst"
    note "linked $dir/"
  fi
done

# ---- 4. CLAUDE.md ------------------------------------------------------
if [[ -f "$REPO/CLAUDE.md" ]]; then
  dst="$CLAUDE_HOME/CLAUDE.md"
  if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$REPO/CLAUDE.md")" ]]; then
    ok "CLAUDE.md linked"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    note "CLAUDE.md not linked"
  else
    [[ -e "$dst" && ! -L "$dst" ]] && mv "$dst" "$dst.bak.$(date +%Y%m%d%H%M%S)"
    rm -f "$dst"; ln -s "$REPO/CLAUDE.md" "$dst"; note "linked CLAUDE.md"
  fi
fi

# ---- 5. verify hooks are runnable -------------------------------------
echo
for h in "$REPO"/hooks/*.sh "$REPO"/bin/*.sh "$REPO"/bin/*.py; do
  [[ -e "$h" ]] || continue
  name=$(basename "$h")
  if [[ ! -x "$h" ]]; then
    if [[ $CHECK_ONLY -eq 1 ]]; then note "$name not executable"
    else chmod +x "$h"; note "chmod +x $name"; fi
  else
    ok "$name executable"
  fi
done

# A hook that cannot run, or that cannot parse its payload, fails OPEN
# upstream (only exit 2 blocks), so prove blocking works end to end through
# the symlink — for every guard, both on a payload it must block and on a
# garbage payload. A guard that is never probed can install broken and the run
# still reports "done.".
#
#   probe_guard <hook> <what it blocks> <payload that must block>
probe_guard() {
  local hook="$1" what="$2" probe="$3" name="${1%.sh}" rc rc_garbage
  if [[ -x "$CLAUDE_HOME/hooks/$hook" ]]; then
    set +e
    printf '%s' "$probe" | "$CLAUDE_HOME/hooks/$hook" >/dev/null 2>&1
    rc=$?
    printf '%s' 'not json' | "$CLAUDE_HOME/hooks/$hook" >/dev/null 2>&1
    rc_garbage=$?
    set -e
    # die, not note: a guard returning anything but 2 is not drift, it is absent.
    # note sets drift=1, which in install mode prints a yellow arrow and then
    # reports "done." — an install that says done while the guards are open is
    # exactly the silent failure ADR 0001 refuses for the observer.
    [[ $rc -eq 2 ]] && ok "$name blocks $what through the symlink" \
                    || die "$name returned $rc, expected 2 — the guards are failing open"
    [[ $rc_garbage -eq 2 ]] && ok "$name fails closed on an unparseable payload" \
                            || die "$name returned $rc_garbage on garbage, expected 2 — fails open"
  else
    # After section 3 links hooks/ and the chmod loop above marks them
    # executable, this branch is unreachable in an install — so reaching it means
    # an invariant broke between here and there, and that must be loud. Under
    # --check, an unlinked hooks/ is ordinary drift and section 3 already noted
    # it; reporting rather than dying is what --check is for.
    if [[ $CHECK_ONLY -eq 1 ]]; then
      note "$hook not linked into $CLAUDE_HOME — guard probe skipped"
    else
      die "$hook not linked into $CLAUDE_HOME after section 3 — refusing to report a successful install with unverified guards"
    fi
  fi
}

# The PEM header is assembled at runtime, as in tests/guard-tests.sh, so no
# literal key header ever appears in this file: guard-secrets would refuse the
# edit that wrote it, and every secret scanner would flag the repo.
pem="-----BEGIN RSA PRIVATE"
pem="$pem KEY-----"
probe_guard guard-bash.sh "a destructive command" \
  '{"tool_name":"Bash","tool_input":{"command":"terraform destroy"}}'
probe_guard guard-paths.sh "a read of a .env file" \
  '{"tool_name":"Read","tool_input":{"file_path":"/x/.env"}}'
probe_guard guard-secrets.sh "a PEM private key in written content" \
  "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"/tmp/x/probe.py\",\"content\":\"KEY = '$pem'\"}}"
# Each enabled signature pack must block its own sample (stage S2, C8). The
# switch comes from the generated settings, not this shell: unset or empty
# means every shipped pack, "none" means no pack.
packs=$(python3 -c 'import json,sys; print(json.load(open(sys.argv[1])).get("env",{}).get("TRIMTAB_SECRET_PACKS",""))' \
        "$CLAUDE_HOME/settings.json" 2>/dev/null || true)
pack_list=()
if [[ -z "$packs" ]]; then
  for f in "$REPO"/hooks/secrets.d/*.patterns; do
    [[ -e "$f" ]] || continue
    f=${f##*/}; pack_list+=("${f%.patterns}")
  done
elif [[ "$packs" != none ]]; then
  IFS=',' read -r -a pack_list <<<"$packs"
fi
for pack in ${pack_list[@]+"${pack_list[@]}"}; do
  probe_file="$REPO/hooks/secrets.d/$pack.probe"
  [[ -r "$probe_file" ]] || die "signature pack $pack has no probe file"
  while IFS= read -r first && IFS= read -r rest; do
    [[ -z "$first" ]] && continue
    sample="$first$rest"
    TRIMTAB_SECRET_PACKS="$pack" probe_guard guard-secrets.sh "a $pack sample" \
      "{\"tool_name\":\"Write\",\"tool_input\":{\"file_path\":\"/tmp/x/probe.py\",\"content\":\"v = '$sample'\"}}"
    IFS= read -r _ || true
  done <"$probe_file"
done
probe_guard guard-security.sh "an edit to a CI workflow" \
  '{"tool_name":"Edit","tool_input":{"file_path":"/tmp/x/.github/workflows/ci.yml"}}'
unset pem

# ---- 6. verify the rule-usage observer records ------------------------
# This hook cannot block anything, so the only failure it can have is
# silence — and silence reads exactly like a quiet week in the weekly
# report. Prove end to end, through the symlink, that a payload becomes a
# record with a measured size on it.
if [[ -x "$CLAUDE_HOME/hooks/rule-usage.sh" ]]; then
  probe_log=$(mktemp -t rule-usage-probe.XXXXXX)
  # Any file in the checkout will do, as long as it exists: the observer
  # records its size, and a missing file records null, which reads as failure.
  # README.md is the one every checkout has (trimtab-core ships no CLAUDE.md).
  probe='{"hook_event_name":"InstructionsLoaded","session_id":"bootstrap-probe","cwd":"/","file_path":"'"$REPO/README.md"'","memory_type":"User","load_reason":"session_start"}'
  set +e
  printf '%s' "$probe" \
    | CLAUDE_RULE_USAGE_LOG="$probe_log" "$CLAUDE_HOME/hooks/rule-usage.sh" >/dev/null 2>&1
  rc_obs=$?
  set -e
  if [[ $rc_obs -eq 0 ]] \
     && grep -q '"event":"InstructionsLoaded"' "$probe_log" 2>/dev/null \
     && grep -q '"bytes":[0-9]' "$probe_log" 2>/dev/null; then
    ok "rule-usage observer records a load through the symlink"
  else
    note "rule-usage observer wrote no usable record (exit $rc_obs) — the weekly report would read as a quiet week"
  fi
  rm -f "$probe_log"
else
  note "rule-usage.sh not linked into $CLAUDE_HOME yet — observer probe skipped"
fi

# ---- 7. weekly report timer -------------------------------------------
# A *user* timer: it runs as the operator, reads only their own log, writes
# only into their own log directory, and is undone with
#   systemctl --user disable --now rule-usage-report.timer
# Skip the whole step with --no-timer on a machine that should not report.
# A user timer lives in the operator's own systemd session, which no
# CLAUDE_CONFIG_DIR can redirect. This step used $HOME unconditionally, so a run
# that had declared itself sandboxed — ci.yml's own bootstrap job sets
# CLAUDE_CONFIG_DIR=/tmp/claude-ci-home — still rewired the operator's systemd
# when it happened on a workstation instead of a runner. Combined with §0 that
# is how the live units came to point into a worktree: enabled, working, and
# one cleanup away from silently never running again. A sandbox gets no timer.
if [[ $WITH_TIMER -eq 1 && $SANDBOXED -eq 1 ]]; then
  echo
  skip "sandboxed run (CLAUDE_CONFIG_DIR is not $HOME/.claude) — timer left alone"
elif [[ $WITH_TIMER -eq 1 && -d "$REPO/systemd" ]] && command -v systemctl >/dev/null 2>&1; then
  echo
  # XDG_CONFIG_HOME is the correct spelling of this location; $HOME/.config is
  # only its default.
  unit_dir="${XDG_CONFIG_HOME:-$HOME/.config}/systemd/user"
  [[ $CHECK_ONLY -eq 1 ]] || mkdir -p "$unit_dir"
  for unit in "$REPO"/systemd/*; do
    [[ -e "$unit" ]] || continue
    uname=$(basename "$unit")
    dst="$unit_dir/$uname"
    if [[ -L "$dst" && "$(readlink -f "$dst")" == "$(readlink -f "$unit")" ]]; then
      ok "$uname linked"
    elif [[ $CHECK_ONLY -eq 1 ]]; then
      # Same reason as the directory links above: a unit pointing into a
      # worktree reads as "not linked", which is how this went undiagnosed.
      if [[ -L "$dst" ]]; then
        note "$uname points at $(readlink "$dst") — expected $unit"
      else
        note "$uname not linked"
      fi
    else
      ln -sfn "$unit" "$dst"
      note "linked $uname"
    fi
  done

  if systemctl --user is-enabled rule-usage-report.timer >/dev/null 2>&1; then
    ok "rule-usage-report.timer enabled"
  elif [[ $CHECK_ONLY -eq 1 ]]; then
    note "rule-usage-report.timer not enabled"
  elif ! systemctl --user daemon-reload >/dev/null 2>&1; then
    note "no user systemd session here — enable it yourself with: systemctl --user enable --now rule-usage-report.timer"
  elif systemctl --user enable --now rule-usage-report.timer >/dev/null 2>&1; then
    note "enabled rule-usage-report.timer (Mondays, 08:00)"
  else
    note "could not enable rule-usage-report.timer — run: systemctl --user enable --now rule-usage-report.timer"
  fi
fi

echo
if [[ $CHECK_ONLY -eq 1 ]]; then
  [[ $drift -eq 1 ]] && { echo "drift detected"; exit 1; } || { echo "in sync"; exit 0; }
fi
echo "done. Run 'claude' and check /hooks to confirm registration."
