"""HARNESS.md: the generated index of every harness item.

`check` fails when the committed file is stale, an ID is duplicated, or an ID
that a previous registry listed has vanished without a withdrawal stub.
"""

from __future__ import annotations

import re
from pathlib import Path

from trimtab.items import Discovery, Item, Problem
from trimtab.registry.rules import RuleType

FILENAME = "HARNESS.md"

# Milestone 1 has one item type. Skills add a line here (plan section 4).
ITEM_TYPES = (RuleType(),)

HEADER = """# Harness items

<!-- Generated by `bin/trimtab registry`. Do not edit by hand: edit the item
     and regenerate. CI fails when this file is stale. -->

Every harness item, by ID. Cite the ID, never the file and heading: IDs are
assigned once and never reused or renumbered. A withdrawn item keeps its row.

| ID | Type | Strength | Source | Heading | Status |
|---|---|---|---|---|---|
"""

ROW_ID = re.compile(r"^\|\s*`([^`]+)`\s*\|", re.M)


def discover(root: Path) -> Discovery:
    items, problems = [], []
    for item_type in ITEM_TYPES:
        found = item_type.discover(Path(root))
        items += found.items
        problems += found.problems
    return Discovery(tuple(items), tuple(problems) + tuple(_duplicates(items)))


def _duplicates(items) -> list[Problem]:
    seen: dict[str, str] = {}
    problems = []
    for item in items:
        if item.id in seen and seen[item.id] != item.source:
            problems.append(Problem("duplicate-id", item.source, f"{item.id} is also defined in {seen[item.id]}"))
        seen.setdefault(item.id, item.source)
    return problems


def _sort_key(item: Item):
    parts = tuple(int(p) if p.isdigit() else 0 for p in item.local_id.split("."))
    return (item.prefix, parts, item.local_id)


def render(items) -> str:
    rows = []
    for item in sorted(items, key=_sort_key):
        heading = item.heading.replace("|", "\\|")
        status = "withdrawn" if item.withdrawn else "active"
        rows.append(f"| `{item.id}` | {item.type} | {item.strength.label} | `{item.source}` | {heading} | {status} |\n")
    return HEADER + "".join(rows)


def listed_ids(text: str) -> set[str]:
    return set(ROW_ID.findall(text))


def _vanished(items, previous: str | None) -> list[Problem]:
    if previous is None:
        return []
    now = {i.id for i in items}
    return [Problem("vanished", item_id, "listed before, now missing; leave a withdrawal stub")
            for item_id in sorted(listed_ids(previous) - now)]


def check(root: Path, previous: str | None = None) -> list[Problem]:
    """Duplicate, vanished (against the committed file and `previous`) and stale."""
    root = Path(root)
    found = discover(root)
    problems = list(found.problems)
    committed = _read(root)
    problems += _vanished(found.items, committed)
    for p in _vanished(found.items, previous):
        if p not in problems:
            problems.append(p)
    if not any(p.code == "vanished" for p in problems) and committed != render(found.items):
        problems.append(Problem("stale", FILENAME, "regenerate with `bin/trimtab registry --instance <dir>`"))
    return problems


def write(root: Path) -> list[Problem]:
    """Regenerate HARNESS.md, refusing when that would drop an ID or hide a duplicate."""
    root = Path(root)
    found = discover(root)
    problems = list(found.problems) + _vanished(found.items, _read(root))
    if problems:
        return problems
    (root / FILENAME).write_text(render(found.items), encoding="utf-8")
    return []


def _read(root: Path) -> str | None:
    path = root / FILENAME
    return path.read_text(encoding="utf-8") if path.is_file() else None
